# Generated by Django 3.2.13 on 2022-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='post_views',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
